// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: kv.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadMode int32

const (
	ReadMode_READ_INDEX ReadMode = 0
	ReadMode_LOG        ReadMode = 1
)

// Enum value maps for ReadMode.
var (
	ReadMode_name = map[int32]string{
		0: "READ_INDEX",
		1: "LOG",
	}
	ReadMode_value = map[string]int32{
		"READ_INDEX": 0,
		"LOG":        1,
	}
)

func (x ReadMode) Enum() *ReadMode {
	p := new(ReadMode)
	*p = x
	return p
}

func (x ReadMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadMode) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_proto_enumTypes[0].Descriptor()
}

func (ReadMode) Type() protoreflect.EnumType {
	return &file_kv_proto_enumTypes[0]
}

func (x ReadMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadMode.Descriptor instead.
func (ReadMode) EnumDescriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

// Command is the payload of a Raft log entry.
type Command struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientId uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq      uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Op:
	//
	//	*Command_Register
	//	*Command_Put
	//	*Command_Delete
	//	*Command_Cas
	//	*Command_Get
	//	*Command_Scan
	//	*Command_Freeze
	//	*Command_Import
	//	*Command_Purge
	Op            isCommand_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Command) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Command) GetOp() isCommand_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Command) GetRegister() *RegisterOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *Command) GetPut() *PutOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *Command) GetDelete() *DeleteOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Command) GetCas() *CasOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Cas); ok {
			return x.Cas
		}
	}
	return nil
}

func (x *Command) GetGet() *GetOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *Command) GetScan() *ScanOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Scan); ok {
			return x.Scan
		}
	}
	return nil
}

func (x *Command) GetFreeze() *FreezeOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Freeze); ok {
			return x.Freeze
		}
	}
	return nil
}

func (x *Command) GetImport() *ImportOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Import); ok {
			return x.Import
		}
	}
	return nil
}

func (x *Command) GetPurge() *PurgeOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Purge); ok {
			return x.Purge
		}
	}
	return nil
}

type isCommand_Op interface {
	isCommand_Op()
}

type Command_Register struct {
	Register *RegisterOp `protobuf:"bytes,3,opt,name=register,proto3,oneof"`
}

type Command_Put struct {
	Put *PutOp `protobuf:"bytes,4,opt,name=put,proto3,oneof"`
}

type Command_Delete struct {
	Delete *DeleteOp `protobuf:"bytes,5,opt,name=delete,proto3,oneof"`
}

type Command_Cas struct {
	Cas *CasOp `protobuf:"bytes,6,opt,name=cas,proto3,oneof"`
}

type Command_Get struct {
	Get *GetOp `protobuf:"bytes,7,opt,name=get,proto3,oneof"`
}

type Command_Scan struct {
	Scan *ScanOp `protobuf:"bytes,8,opt,name=scan,proto3,oneof"`
}

type Command_Freeze struct {
	Freeze *FreezeOp `protobuf:"bytes,9,opt,name=freeze,proto3,oneof"`
}

type Command_Import struct {
	Import *ImportOp `protobuf:"bytes,10,opt,name=import,proto3,oneof"`
}

type Command_Purge struct {
	Purge *PurgeOp `protobuf:"bytes,11,opt,name=purge,proto3,oneof"`
}

func (*Command_Register) isCommand_Op() {}

func (*Command_Put) isCommand_Op() {}

func (*Command_Delete) isCommand_Op() {}

func (*Command_Cas) isCommand_Op() {}

func (*Command_Get) isCommand_Op() {}

func (*Command_Scan) isCommand_Op() {}

func (*Command_Freeze) isCommand_Op() {}

func (*Command_Import) isCommand_Op() {}

func (*Command_Purge) isCommand_Op() {}

// FreezeOp stops writes to one shard in this group while it is copied
// elsewhere.
type FreezeOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         uint32                 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeOp) Reset() {
	*x = FreezeOp{}
	mi := &file_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeOp) ProtoMessage() {}

func (x *FreezeOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeOp.ProtoReflect.Descriptor instead.
func (*FreezeOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{1}
}

func (x *FreezeOp) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

// ImportOp loads a moved shard's keys into this group and takes ownership.
type ImportOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         uint32                 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Kvs           []*KeyValue            `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
	Last          bool                   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportOp) Reset() {
	*x = ImportOp{}
	mi := &file_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportOp) ProtoMessage() {}

func (x *ImportOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportOp.ProtoReflect.Descriptor instead.
func (*ImportOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{2}
}

func (x *ImportOp) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *ImportOp) GetKvs() []*KeyValue {
	if x != nil {
		return x.Kvs
	}
	return nil
}

func (x *ImportOp) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

// PurgeOp deletes a shard's keys after it has moved away; the shard stays
// closed here so a stale router cannot write to it.
type PurgeOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         uint32                 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeOp) Reset() {
	*x = PurgeOp{}
	mi := &file_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeOp) ProtoMessage() {}

func (x *PurgeOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeOp.ProtoReflect.Descriptor instead.
func (*PurgeOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PurgeOp) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

type RegisterOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterOp) Reset() {
	*x = RegisterOp{}
	mi := &file_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOp) ProtoMessage() {}

func (x *RegisterOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOp.ProtoReflect.Descriptor instead.
func (*RegisterOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{4}
}

type PutOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutOp) Reset() {
	*x = PutOp{}
	mi := &file_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutOp) ProtoMessage() {}

func (x *PutOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutOp.ProtoReflect.Descriptor instead.
func (*PutOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{5}
}

func (x *PutOp) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutOp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeleteOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOp) Reset() {
	*x = DeleteOp{}
	mi := &file_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOp) ProtoMessage() {}

func (x *DeleteOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOp.ProtoReflect.Descriptor instead.
func (*DeleteOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteOp) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// CasOp replaces the value only if the current value equals expected; an
// unset expected means the key must be absent.
type CasOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Expected      []byte                 `protobuf:"bytes,2,opt,name=expected,proto3,oneof" json:"expected,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CasOp) Reset() {
	*x = CasOp{}
	mi := &file_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CasOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasOp) ProtoMessage() {}

func (x *CasOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasOp.ProtoReflect.Descriptor instead.
func (*CasOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{7}
}

func (x *CasOp) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CasOp) GetExpected() []byte {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *CasOp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOp) Reset() {
	*x = GetOp{}
	mi := &file_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOp) ProtoMessage() {}

func (x *GetOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOp.ProtoReflect.Descriptor instead.
func (*GetOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{8}
}

func (x *GetOp) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ScanOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           []byte                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	MaxBytes      uint32                 `protobuf:"varint,4,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanOp) Reset() {
	*x = ScanOp{}
	mi := &file_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanOp) ProtoMessage() {}

func (x *ScanOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanOp.ProtoReflect.Descriptor instead.
func (*ScanOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{9}
}

func (x *ScanOp) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ScanOp) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ScanOp) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ScanOp) GetMaxBytes() uint32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{10}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Result is what applying a Command produced. It is cached per session so
// a retried command returns the same answer.
type Result struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Found    bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value    []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Success  bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ClientId uint64                 `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Kvs      []*KeyValue            `protobuf:"bytes,5,rep,name=kvs,proto3" json:"kvs,omitempty"`
	// moving reports that the key's shard is not writable here right now.
	Moving        bool `protobuf:"varint,6,opt,name=moving,proto3" json:"moving,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{11}
}

func (x *Result) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *Result) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Result) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Result) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Result) GetKvs() []*KeyValue {
	if x != nil {
		return x.Kvs
	}
	return nil
}

func (x *Result) GetMoving() bool {
	if x != nil {
		return x.Moving
	}
	return false
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_kv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{12}
}

func (x *Session) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Session) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// A request names the Raft group it is for. Zero lets the receiving node
// route it by key through the shard map.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         uint64                 `protobuf:"varint,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_kv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterRequest) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_kv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterResponse) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Mode          ReadMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=keystone.ReadMode" json:"mode,omitempty"`
	Session       *Session               `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	Group         uint64                 `protobuf:"varint,4,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_kv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{15}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRequest) GetMode() ReadMode {
	if x != nil {
		return x.Mode
	}
	return ReadMode_READ_INDEX
}

func (x *GetRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetRequest) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_kv_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{16}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Group         uint64                 `protobuf:"varint,4,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_kv_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{17}
}

func (x *PutRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_kv_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{18}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Group         uint64                 `protobuf:"varint,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_kv_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRequest) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_kv_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{20}
}

type CasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Expected      []byte                 `protobuf:"bytes,3,opt,name=expected,proto3,oneof" json:"expected,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Group         uint64                 `protobuf:"varint,5,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CasRequest) Reset() {
	*x = CasRequest{}
	mi := &file_kv_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasRequest) ProtoMessage() {}

func (x *CasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasRequest.ProtoReflect.Descriptor instead.
func (*CasRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{21}
}

func (x *CasRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *CasRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CasRequest) GetExpected() []byte {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *CasRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CasRequest) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

type CasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Current       []byte                 `protobuf:"bytes,3,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CasResponse) Reset() {
	*x = CasResponse{}
	mi := &file_kv_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasResponse) ProtoMessage() {}

func (x *CasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasResponse.ProtoReflect.Descriptor instead.
func (*CasResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{22}
}

func (x *CasResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CasResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *CasResponse) GetCurrent() []byte {
	if x != nil {
		return x.Current
	}
	return nil
}

type ScanRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Start   []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End     []byte                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Limit   uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Mode    ReadMode               `protobuf:"varint,4,opt,name=mode,proto3,enum=keystone.ReadMode" json:"mode,omitempty"`
	Session *Session               `protobuf:"bytes,5,opt,name=session,proto3" json:"session,omitempty"`
	Group   uint64                 `protobuf:"varint,6,opt,name=group,proto3" json:"group,omitempty"`
	// max_bytes ends the scan once the keys and values returned reach it; the
	// pair that crosses it is still included, so a scan always advances. Zero
	// means no bound. A caller paging through large values sets it to keep a
	// page under what gRPC will carry.
	MaxBytes      uint32 `protobuf:"varint,7,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_kv_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{23}
}

func (x *ScanRequest) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ScanRequest) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ScanRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ScanRequest) GetMode() ReadMode {
	if x != nil {
		return x.Mode
	}
	return ReadMode_READ_INDEX
}

func (x *ScanRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ScanRequest) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *ScanRequest) GetMaxBytes() uint32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kvs           []*KeyValue            `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_kv_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{24}
}

func (x *ScanResponse) GetKvs() []*KeyValue {
	if x != nil {
		return x.Kvs
	}
	return nil
}

// NotLeader is attached to a FailedPrecondition status so the client can
// go straight to the leader.
type NotLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      uint64                 `protobuf:"varint,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,2,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotLeader) Reset() {
	*x = NotLeader{}
	mi := &file_kv_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotLeader) ProtoMessage() {}

func (x *NotLeader) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotLeader.ProtoReflect.Descriptor instead.
func (*NotLeader) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{25}
}

func (x *NotLeader) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *NotLeader) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

// ShardMap is stored in the meta group: element i is the group serving
// shard i, and moving[i] names the group it is moving to, or zero.
type ShardMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []uint64               `protobuf:"varint,1,rep,packed,name=groups,proto3" json:"groups,omitempty"`
	Moving        []uint64               `protobuf:"varint,2,rep,packed,name=moving,proto3" json:"moving,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardMap) Reset() {
	*x = ShardMap{}
	mi := &file_kv_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardMap) ProtoMessage() {}

func (x *ShardMap) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardMap.ProtoReflect.Descriptor instead.
func (*ShardMap) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{26}
}

func (x *ShardMap) GetGroups() []uint64 {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ShardMap) GetMoving() []uint64 {
	if x != nil {
		return x.Moving
	}
	return nil
}

// AdminRequest runs a shard management command in one group's log.
type AdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         uint64                 `protobuf:"varint,1,opt,name=group,proto3" json:"group,omitempty"`
	Command       *Command               `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRequest) Reset() {
	*x = AdminRequest{}
	mi := &file_kv_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRequest) ProtoMessage() {}

func (x *AdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRequest.ProtoReflect.Descriptor instead.
func (*AdminRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{27}
}

func (x *AdminRequest) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *AdminRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type AdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Result                `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminResponse) Reset() {
	*x = AdminResponse{}
	mi := &file_kv_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResponse) ProtoMessage() {}

func (x *AdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResponse.ProtoReflect.Descriptor instead.
func (*AdminResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{28}
}

func (x *AdminResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type MoveShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         uint32                 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Group         uint64                 `protobuf:"varint,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveShardRequest) Reset() {
	*x = MoveShardRequest{}
	mi := &file_kv_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveShardRequest) ProtoMessage() {}

func (x *MoveShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveShardRequest.ProtoReflect.Descriptor instead.
func (*MoveShardRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{29}
}

func (x *MoveShardRequest) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *MoveShardRequest) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

type MoveShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveShardResponse) Reset() {
	*x = MoveShardResponse{}
	mi := &file_kv_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveShardResponse) ProtoMessage() {}

func (x *MoveShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveShardResponse.ProtoReflect.Descriptor instead.
func (*MoveShardResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{30}
}

type ShardMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardMapRequest) Reset() {
	*x = ShardMapRequest{}
	mi := &file_kv_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardMapRequest) ProtoMessage() {}

func (x *ShardMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardMapRequest.ProtoReflect.Descriptor instead.
func (*ShardMapRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{31}
}

var File_kv_proto protoreflect.FileDescriptor

const file_kv_proto_rawDesc = "" +
	"\n" +
	"\bkv.proto\x12\bkeystone\"\xbe\x03\n" +
	"\aCommand\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x122\n" +
	"\bregister\x18\x03 \x01(\v2\x14.keystone.RegisterOpH\x00R\bregister\x12#\n" +
	"\x03put\x18\x04 \x01(\v2\x0f.keystone.PutOpH\x00R\x03put\x12,\n" +
	"\x06delete\x18\x05 \x01(\v2\x12.keystone.DeleteOpH\x00R\x06delete\x12#\n" +
	"\x03cas\x18\x06 \x01(\v2\x0f.keystone.CasOpH\x00R\x03cas\x12#\n" +
	"\x03get\x18\a \x01(\v2\x0f.keystone.GetOpH\x00R\x03get\x12&\n" +
	"\x04scan\x18\b \x01(\v2\x10.keystone.ScanOpH\x00R\x04scan\x12,\n" +
	"\x06freeze\x18\t \x01(\v2\x12.keystone.FreezeOpH\x00R\x06freeze\x12,\n" +
	"\x06import\x18\n" +
	" \x01(\v2\x12.keystone.ImportOpH\x00R\x06import\x12)\n" +
	"\x05purge\x18\v \x01(\v2\x11.keystone.PurgeOpH\x00R\x05purgeB\x04\n" +
	"\x02op\" \n" +
	"\bFreezeOp\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\rR\x05shard\"Z\n" +
	"\bImportOp\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\rR\x05shard\x12$\n" +
	"\x03kvs\x18\x02 \x03(\v2\x12.keystone.KeyValueR\x03kvs\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last\"\x1f\n" +
	"\aPurgeOp\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\rR\x05shard\"\f\n" +
	"\n" +
	"RegisterOp\"/\n" +
	"\x05PutOp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x1c\n" +
	"\bDeleteOp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"]\n" +
	"\x05CasOp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1f\n" +
	"\bexpected\x18\x02 \x01(\fH\x00R\bexpected\x88\x01\x01\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05valueB\v\n" +
	"\t_expected\"\x19\n" +
	"\x05GetOp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"c\n" +
	"\x06ScanOp\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\fR\x03end\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x1b\n" +
	"\tmax_bytes\x18\x04 \x01(\rR\bmaxBytes\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xa9\x01\n" +
	"\x06Result\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x04R\bclientId\x12$\n" +
	"\x03kvs\x18\x05 \x03(\v2\x12.keystone.KeyValueR\x03kvs\x12\x16\n" +
	"\x06moving\x18\x06 \x01(\bR\x06moving\"8\n" +
	"\aSession\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"'\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\x04R\x05group\"/\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\"\x89\x01\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12&\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x12.keystone.ReadModeR\x04mode\x12+\n" +
	"\asession\x18\x03 \x01(\v2\x11.keystone.SessionR\asession\x12\x14\n" +
	"\x05group\x18\x04 \x01(\x04R\x05group\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"w\n" +
	"\n" +
	"PutRequest\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.keystone.SessionR\asession\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x14\n" +
	"\x05group\x18\x04 \x01(\x04R\x05group\"\r\n" +
	"\vPutResponse\"d\n" +
	"\rDeleteRequest\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.keystone.SessionR\asession\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05group\x18\x03 \x01(\x04R\x05group\"\x10\n" +
	"\x0eDeleteResponse\"\xa5\x01\n" +
	"\n" +
	"CasRequest\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.keystone.SessionR\asession\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x1f\n" +
	"\bexpected\x18\x03 \x01(\fH\x00R\bexpected\x88\x01\x01\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x14\n" +
	"\x05group\x18\x05 \x01(\x04R\x05groupB\v\n" +
	"\t_expected\"W\n" +
	"\vCasResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x18\n" +
	"\acurrent\x18\x03 \x01(\fR\acurrent\"\xd3\x01\n" +
	"\vScanRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\fR\x03end\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12&\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x12.keystone.ReadModeR\x04mode\x12+\n" +
	"\asession\x18\x05 \x01(\v2\x11.keystone.SessionR\asession\x12\x14\n" +
	"\x05group\x18\x06 \x01(\x04R\x05group\x12\x1b\n" +
	"\tmax_bytes\x18\a \x01(\rR\bmaxBytes\"4\n" +
	"\fScanResponse\x12$\n" +
	"\x03kvs\x18\x01 \x03(\v2\x12.keystone.KeyValueR\x03kvs\"I\n" +
	"\tNotLeader\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\x04R\bleaderId\x12\x1f\n" +
	"\vleader_addr\x18\x02 \x01(\tR\n" +
	"leaderAddr\":\n" +
	"\bShardMap\x12\x16\n" +
	"\x06groups\x18\x01 \x03(\x04R\x06groups\x12\x16\n" +
	"\x06moving\x18\x02 \x03(\x04R\x06moving\"Q\n" +
	"\fAdminRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\x04R\x05group\x12+\n" +
	"\acommand\x18\x02 \x01(\v2\x11.keystone.CommandR\acommand\"9\n" +
	"\rAdminResponse\x12(\n" +
	"\x06result\x18\x01 \x01(\v2\x10.keystone.ResultR\x06result\">\n" +
	"\x10MoveShardRequest\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\rR\x05shard\x12\x14\n" +
	"\x05group\x18\x02 \x01(\x04R\x05group\"\x13\n" +
	"\x11MoveShardResponse\"\x11\n" +
	"\x0fShardMapRequest*#\n" +
	"\bReadMode\x12\x0e\n" +
	"\n" +
	"READ_INDEX\x10\x00\x12\a\n" +
	"\x03LOG\x10\x012\x9b\x04\n" +
	"\x02KV\x12G\n" +
	"\x0eRegisterClient\x12\x19.keystone.RegisterRequest\x1a\x1a.keystone.RegisterResponse\x122\n" +
	"\x03Get\x12\x14.keystone.GetRequest\x1a\x15.keystone.GetResponse\x122\n" +
	"\x03Put\x12\x14.keystone.PutRequest\x1a\x15.keystone.PutResponse\x12;\n" +
	"\x06Delete\x12\x17.keystone.DeleteRequest\x1a\x18.keystone.DeleteResponse\x122\n" +
	"\x03Cas\x12\x14.keystone.CasRequest\x1a\x15.keystone.CasResponse\x125\n" +
	"\x04Scan\x12\x15.keystone.ScanRequest\x1a\x16.keystone.ScanResponse\x128\n" +
	"\x05Admin\x12\x16.keystone.AdminRequest\x1a\x17.keystone.AdminResponse\x12D\n" +
	"\tMoveShard\x12\x1a.keystone.MoveShardRequest\x1a\x1b.keystone.MoveShardResponse\x12<\n" +
	"\vGetShardMap\x12\x19.keystone.ShardMapRequest\x1a\x12.keystone.ShardMapB'Z%github.com/arifisme/keystone/proto;pbb\x06proto3"

var (
	file_kv_proto_rawDescOnce sync.Once
	file_kv_proto_rawDescData []byte
)

func file_kv_proto_rawDescGZIP() []byte {
	file_kv_proto_rawDescOnce.Do(func() {
		file_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)))
	})
	return file_kv_proto_rawDescData
}

var file_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_kv_proto_goTypes = []any{
	(ReadMode)(0),             // 0: keystone.ReadMode
	(*Command)(nil),           // 1: keystone.Command
	(*FreezeOp)(nil),          // 2: keystone.FreezeOp
	(*ImportOp)(nil),          // 3: keystone.ImportOp
	(*PurgeOp)(nil),           // 4: keystone.PurgeOp
	(*RegisterOp)(nil),        // 5: keystone.RegisterOp
	(*PutOp)(nil),             // 6: keystone.PutOp
	(*DeleteOp)(nil),          // 7: keystone.DeleteOp
	(*CasOp)(nil),             // 8: keystone.CasOp
	(*GetOp)(nil),             // 9: keystone.GetOp
	(*ScanOp)(nil),            // 10: keystone.ScanOp
	(*KeyValue)(nil),          // 11: keystone.KeyValue
	(*Result)(nil),            // 12: keystone.Result
	(*Session)(nil),           // 13: keystone.Session
	(*RegisterRequest)(nil),   // 14: keystone.RegisterRequest
	(*RegisterResponse)(nil),  // 15: keystone.RegisterResponse
	(*GetRequest)(nil),        // 16: keystone.GetRequest
	(*GetResponse)(nil),       // 17: keystone.GetResponse
	(*PutRequest)(nil),        // 18: keystone.PutRequest
	(*PutResponse)(nil),       // 19: keystone.PutResponse
	(*DeleteRequest)(nil),     // 20: keystone.DeleteRequest
	(*DeleteResponse)(nil),    // 21: keystone.DeleteResponse
	(*CasRequest)(nil),        // 22: keystone.CasRequest
	(*CasResponse)(nil),       // 23: keystone.CasResponse
	(*ScanRequest)(nil),       // 24: keystone.ScanRequest
	(*ScanResponse)(nil),      // 25: keystone.ScanResponse
	(*NotLeader)(nil),         // 26: keystone.NotLeader
	(*ShardMap)(nil),          // 27: keystone.ShardMap
	(*AdminRequest)(nil),      // 28: keystone.AdminRequest
	(*AdminResponse)(nil),     // 29: keystone.AdminResponse
	(*MoveShardRequest)(nil),  // 30: keystone.MoveShardRequest
	(*MoveShardResponse)(nil), // 31: keystone.MoveShardResponse
	(*ShardMapRequest)(nil),   // 32: keystone.ShardMapRequest
}
var file_kv_proto_depIdxs = []int32{
	5,  // 0: keystone.Command.register:type_name -> keystone.RegisterOp
	6,  // 1: keystone.Command.put:type_name -> keystone.PutOp
	7,  // 2: keystone.Command.delete:type_name -> keystone.DeleteOp
	8,  // 3: keystone.Command.cas:type_name -> keystone.CasOp
	9,  // 4: keystone.Command.get:type_name -> keystone.GetOp
	10, // 5: keystone.Command.scan:type_name -> keystone.ScanOp
	2,  // 6: keystone.Command.freeze:type_name -> keystone.FreezeOp
	3,  // 7: keystone.Command.import:type_name -> keystone.ImportOp
	4,  // 8: keystone.Command.purge:type_name -> keystone.PurgeOp
	11, // 9: keystone.ImportOp.kvs:type_name -> keystone.KeyValue
	11, // 10: keystone.Result.kvs:type_name -> keystone.KeyValue
	0,  // 11: keystone.GetRequest.mode:type_name -> keystone.ReadMode
	13, // 12: keystone.GetRequest.session:type_name -> keystone.Session
	13, // 13: keystone.PutRequest.session:type_name -> keystone.Session
	13, // 14: keystone.DeleteRequest.session:type_name -> keystone.Session
	13, // 15: keystone.CasRequest.session:type_name -> keystone.Session
	0,  // 16: keystone.ScanRequest.mode:type_name -> keystone.ReadMode
	13, // 17: keystone.ScanRequest.session:type_name -> keystone.Session
	11, // 18: keystone.ScanResponse.kvs:type_name -> keystone.KeyValue
	1,  // 19: keystone.AdminRequest.command:type_name -> keystone.Command
	12, // 20: keystone.AdminResponse.result:type_name -> keystone.Result
	14, // 21: keystone.KV.RegisterClient:input_type -> keystone.RegisterRequest
	16, // 22: keystone.KV.Get:input_type -> keystone.GetRequest
	18, // 23: keystone.KV.Put:input_type -> keystone.PutRequest
	20, // 24: keystone.KV.Delete:input_type -> keystone.DeleteRequest
	22, // 25: keystone.KV.Cas:input_type -> keystone.CasRequest
	24, // 26: keystone.KV.Scan:input_type -> keystone.ScanRequest
	28, // 27: keystone.KV.Admin:input_type -> keystone.AdminRequest
	30, // 28: keystone.KV.MoveShard:input_type -> keystone.MoveShardRequest
	32, // 29: keystone.KV.GetShardMap:input_type -> keystone.ShardMapRequest
	15, // 30: keystone.KV.RegisterClient:output_type -> keystone.RegisterResponse
	17, // 31: keystone.KV.Get:output_type -> keystone.GetResponse
	19, // 32: keystone.KV.Put:output_type -> keystone.PutResponse
	21, // 33: keystone.KV.Delete:output_type -> keystone.DeleteResponse
	23, // 34: keystone.KV.Cas:output_type -> keystone.CasResponse
	25, // 35: keystone.KV.Scan:output_type -> keystone.ScanResponse
	29, // 36: keystone.KV.Admin:output_type -> keystone.AdminResponse
	31, // 37: keystone.KV.MoveShard:output_type -> keystone.MoveShardResponse
	27, // 38: keystone.KV.GetShardMap:output_type -> keystone.ShardMap
	30, // [30:39] is the sub-list for method output_type
	21, // [21:30] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_kv_proto_init() }
func file_kv_proto_init() {
	if File_kv_proto != nil {
		return
	}
	file_kv_proto_msgTypes[0].OneofWrappers = []any{
		(*Command_Register)(nil),
		(*Command_Put)(nil),
		(*Command_Delete)(nil),
		(*Command_Cas)(nil),
		(*Command_Get)(nil),
		(*Command_Scan)(nil),
		(*Command_Freeze)(nil),
		(*Command_Import)(nil),
		(*Command_Purge)(nil),
	}
	file_kv_proto_msgTypes[7].OneofWrappers = []any{}
	file_kv_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kv_proto_goTypes,
		DependencyIndexes: file_kv_proto_depIdxs,
		EnumInfos:         file_kv_proto_enumTypes,
		MessageInfos:      file_kv_proto_msgTypes,
	}.Build()
	File_kv_proto = out.File
	file_kv_proto_goTypes = nil
	file_kv_proto_depIdxs = nil
}
