// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: kv.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadMode int32

const (
	ReadMode_READ_INDEX ReadMode = 0
	ReadMode_LOG        ReadMode = 1
)

// Enum value maps for ReadMode.
var (
	ReadMode_name = map[int32]string{
		0: "READ_INDEX",
		1: "LOG",
	}
	ReadMode_value = map[string]int32{
		"READ_INDEX": 0,
		"LOG":        1,
	}
)

func (x ReadMode) Enum() *ReadMode {
	p := new(ReadMode)
	*p = x
	return p
}

func (x ReadMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadMode) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_proto_enumTypes[0].Descriptor()
}

func (ReadMode) Type() protoreflect.EnumType {
	return &file_kv_proto_enumTypes[0]
}

func (x ReadMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadMode.Descriptor instead.
func (ReadMode) EnumDescriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

// Command is the payload of a Raft log entry.
type Command struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientId uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq      uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Op:
	//
	//	*Command_Register
	//	*Command_Put
	//	*Command_Delete
	//	*Command_Cas
	//	*Command_Get
	//	*Command_Scan
	Op            isCommand_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Command) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Command) GetOp() isCommand_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Command) GetRegister() *RegisterOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *Command) GetPut() *PutOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *Command) GetDelete() *DeleteOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Command) GetCas() *CasOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Cas); ok {
			return x.Cas
		}
	}
	return nil
}

func (x *Command) GetGet() *GetOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *Command) GetScan() *ScanOp {
	if x != nil {
		if x, ok := x.Op.(*Command_Scan); ok {
			return x.Scan
		}
	}
	return nil
}

type isCommand_Op interface {
	isCommand_Op()
}

type Command_Register struct {
	Register *RegisterOp `protobuf:"bytes,3,opt,name=register,proto3,oneof"`
}

type Command_Put struct {
	Put *PutOp `protobuf:"bytes,4,opt,name=put,proto3,oneof"`
}

type Command_Delete struct {
	Delete *DeleteOp `protobuf:"bytes,5,opt,name=delete,proto3,oneof"`
}

type Command_Cas struct {
	Cas *CasOp `protobuf:"bytes,6,opt,name=cas,proto3,oneof"`
}

type Command_Get struct {
	Get *GetOp `protobuf:"bytes,7,opt,name=get,proto3,oneof"`
}

type Command_Scan struct {
	Scan *ScanOp `protobuf:"bytes,8,opt,name=scan,proto3,oneof"`
}

func (*Command_Register) isCommand_Op() {}

func (*Command_Put) isCommand_Op() {}

func (*Command_Delete) isCommand_Op() {}

func (*Command_Cas) isCommand_Op() {}

func (*Command_Get) isCommand_Op() {}

func (*Command_Scan) isCommand_Op() {}

type RegisterOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterOp) Reset() {
	*x = RegisterOp{}
	mi := &file_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOp) ProtoMessage() {}

func (x *RegisterOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOp.ProtoReflect.Descriptor instead.
func (*RegisterOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{1}
}

type PutOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutOp) Reset() {
	*x = PutOp{}
	mi := &file_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutOp) ProtoMessage() {}

func (x *PutOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutOp.ProtoReflect.Descriptor instead.
func (*PutOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{2}
}

func (x *PutOp) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutOp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeleteOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOp) Reset() {
	*x = DeleteOp{}
	mi := &file_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOp) ProtoMessage() {}

func (x *DeleteOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOp.ProtoReflect.Descriptor instead.
func (*DeleteOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteOp) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// CasOp replaces the value only if the current value equals expected; an
// unset expected means the key must be absent.
type CasOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Expected      []byte                 `protobuf:"bytes,2,opt,name=expected,proto3,oneof" json:"expected,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CasOp) Reset() {
	*x = CasOp{}
	mi := &file_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CasOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasOp) ProtoMessage() {}

func (x *CasOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasOp.ProtoReflect.Descriptor instead.
func (*CasOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{4}
}

func (x *CasOp) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CasOp) GetExpected() []byte {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *CasOp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOp) Reset() {
	*x = GetOp{}
	mi := &file_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOp) ProtoMessage() {}

func (x *GetOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOp.ProtoReflect.Descriptor instead.
func (*GetOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{5}
}

func (x *GetOp) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ScanOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           []byte                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanOp) Reset() {
	*x = ScanOp{}
	mi := &file_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanOp) ProtoMessage() {}

func (x *ScanOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanOp.ProtoReflect.Descriptor instead.
func (*ScanOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{6}
}

func (x *ScanOp) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ScanOp) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ScanOp) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{7}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Result is what applying a Command produced. It is cached per session so
// a retried command returns the same answer.
type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ClientId      uint64                 `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Kvs           []*KeyValue            `protobuf:"bytes,5,rep,name=kvs,proto3" json:"kvs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{8}
}

func (x *Result) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *Result) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Result) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Result) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Result) GetKvs() []*KeyValue {
	if x != nil {
		return x.Kvs
	}
	return nil
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{9}
}

func (x *Session) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Session) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{10}
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterResponse) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Mode          ReadMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=keystone.ReadMode" json:"mode,omitempty"`
	Session       *Session               `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_kv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{12}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRequest) GetMode() ReadMode {
	if x != nil {
		return x.Mode
	}
	return ReadMode_READ_INDEX
}

func (x *GetRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_kv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{13}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_kv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{14}
}

func (x *PutRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_kv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{15}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_kv_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_kv_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{17}
}

type CasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Expected      []byte                 `protobuf:"bytes,3,opt,name=expected,proto3,oneof" json:"expected,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CasRequest) Reset() {
	*x = CasRequest{}
	mi := &file_kv_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasRequest) ProtoMessage() {}

func (x *CasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasRequest.ProtoReflect.Descriptor instead.
func (*CasRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{18}
}

func (x *CasRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *CasRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CasRequest) GetExpected() []byte {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *CasRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Current       []byte                 `protobuf:"bytes,3,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CasResponse) Reset() {
	*x = CasResponse{}
	mi := &file_kv_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasResponse) ProtoMessage() {}

func (x *CasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasResponse.ProtoReflect.Descriptor instead.
func (*CasResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{19}
}

func (x *CasResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CasResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *CasResponse) GetCurrent() []byte {
	if x != nil {
		return x.Current
	}
	return nil
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           []byte                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Mode          ReadMode               `protobuf:"varint,4,opt,name=mode,proto3,enum=keystone.ReadMode" json:"mode,omitempty"`
	Session       *Session               `protobuf:"bytes,5,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_kv_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{20}
}

func (x *ScanRequest) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ScanRequest) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ScanRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ScanRequest) GetMode() ReadMode {
	if x != nil {
		return x.Mode
	}
	return ReadMode_READ_INDEX
}

func (x *ScanRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kvs           []*KeyValue            `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_kv_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{21}
}

func (x *ScanResponse) GetKvs() []*KeyValue {
	if x != nil {
		return x.Kvs
	}
	return nil
}

// NotLeader is attached to a FailedPrecondition status so the client can
// go straight to the leader.
type NotLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      uint64                 `protobuf:"varint,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,2,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotLeader) Reset() {
	*x = NotLeader{}
	mi := &file_kv_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotLeader) ProtoMessage() {}

func (x *NotLeader) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotLeader.ProtoReflect.Descriptor instead.
func (*NotLeader) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{22}
}

func (x *NotLeader) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *NotLeader) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

var File_kv_proto protoreflect.FileDescriptor

const file_kv_proto_rawDesc = "" +
	"\n" +
	"\bkv.proto\x12\bkeystone\"\xb7\x02\n" +
	"\aCommand\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x122\n" +
	"\bregister\x18\x03 \x01(\v2\x14.keystone.RegisterOpH\x00R\bregister\x12#\n" +
	"\x03put\x18\x04 \x01(\v2\x0f.keystone.PutOpH\x00R\x03put\x12,\n" +
	"\x06delete\x18\x05 \x01(\v2\x12.keystone.DeleteOpH\x00R\x06delete\x12#\n" +
	"\x03cas\x18\x06 \x01(\v2\x0f.keystone.CasOpH\x00R\x03cas\x12#\n" +
	"\x03get\x18\a \x01(\v2\x0f.keystone.GetOpH\x00R\x03get\x12&\n" +
	"\x04scan\x18\b \x01(\v2\x10.keystone.ScanOpH\x00R\x04scanB\x04\n" +
	"\x02op\"\f\n" +
	"\n" +
	"RegisterOp\"/\n" +
	"\x05PutOp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x1c\n" +
	"\bDeleteOp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"]\n" +
	"\x05CasOp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1f\n" +
	"\bexpected\x18\x02 \x01(\fH\x00R\bexpected\x88\x01\x01\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05valueB\v\n" +
	"\t_expected\"\x19\n" +
	"\x05GetOp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"F\n" +
	"\x06ScanOp\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\fR\x03end\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x91\x01\n" +
	"\x06Result\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x04R\bclientId\x12$\n" +
	"\x03kvs\x18\x05 \x03(\v2\x12.keystone.KeyValueR\x03kvs\"8\n" +
	"\aSession\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"\x11\n" +
	"\x0fRegisterRequest\"/\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\"s\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12&\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x12.keystone.ReadModeR\x04mode\x12+\n" +
	"\asession\x18\x03 \x01(\v2\x11.keystone.SessionR\asession\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"a\n" +
	"\n" +
	"PutRequest\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.keystone.SessionR\asession\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\r\n" +
	"\vPutResponse\"N\n" +
	"\rDeleteRequest\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.keystone.SessionR\asession\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"\x8f\x01\n" +
	"\n" +
	"CasRequest\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.keystone.SessionR\asession\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x1f\n" +
	"\bexpected\x18\x03 \x01(\fH\x00R\bexpected\x88\x01\x01\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05valueB\v\n" +
	"\t_expected\"W\n" +
	"\vCasResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x18\n" +
	"\acurrent\x18\x03 \x01(\fR\acurrent\"\xa0\x01\n" +
	"\vScanRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\fR\x03end\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12&\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x12.keystone.ReadModeR\x04mode\x12+\n" +
	"\asession\x18\x05 \x01(\v2\x11.keystone.SessionR\asession\"4\n" +
	"\fScanResponse\x12$\n" +
	"\x03kvs\x18\x01 \x03(\v2\x12.keystone.KeyValueR\x03kvs\"I\n" +
	"\tNotLeader\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\x04R\bleaderId\x12\x1f\n" +
	"\vleader_addr\x18\x02 \x01(\tR\n" +
	"leaderAddr*#\n" +
	"\bReadMode\x12\x0e\n" +
	"\n" +
	"READ_INDEX\x10\x00\x12\a\n" +
	"\x03LOG\x10\x012\xd7\x02\n" +
	"\x02KV\x12A\n" +
	"\bRegister\x12\x19.keystone.RegisterRequest\x1a\x1a.keystone.RegisterResponse\x122\n" +
	"\x03Get\x12\x14.keystone.GetRequest\x1a\x15.keystone.GetResponse\x122\n" +
	"\x03Put\x12\x14.keystone.PutRequest\x1a\x15.keystone.PutResponse\x12;\n" +
	"\x06Delete\x12\x17.keystone.DeleteRequest\x1a\x18.keystone.DeleteResponse\x122\n" +
	"\x03Cas\x12\x14.keystone.CasRequest\x1a\x15.keystone.CasResponse\x125\n" +
	"\x04Scan\x12\x15.keystone.ScanRequest\x1a\x16.keystone.ScanResponseB'Z%github.com/arifisme/keystone/proto;pbb\x06proto3"

var (
	file_kv_proto_rawDescOnce sync.Once
	file_kv_proto_rawDescData []byte
)

func file_kv_proto_rawDescGZIP() []byte {
	file_kv_proto_rawDescOnce.Do(func() {
		file_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)))
	})
	return file_kv_proto_rawDescData
}

var file_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_kv_proto_goTypes = []any{
	(ReadMode)(0),            // 0: keystone.ReadMode
	(*Command)(nil),          // 1: keystone.Command
	(*RegisterOp)(nil),       // 2: keystone.RegisterOp
	(*PutOp)(nil),            // 3: keystone.PutOp
	(*DeleteOp)(nil),         // 4: keystone.DeleteOp
	(*CasOp)(nil),            // 5: keystone.CasOp
	(*GetOp)(nil),            // 6: keystone.GetOp
	(*ScanOp)(nil),           // 7: keystone.ScanOp
	(*KeyValue)(nil),         // 8: keystone.KeyValue
	(*Result)(nil),           // 9: keystone.Result
	(*Session)(nil),          // 10: keystone.Session
	(*RegisterRequest)(nil),  // 11: keystone.RegisterRequest
	(*RegisterResponse)(nil), // 12: keystone.RegisterResponse
	(*GetRequest)(nil),       // 13: keystone.GetRequest
	(*GetResponse)(nil),      // 14: keystone.GetResponse
	(*PutRequest)(nil),       // 15: keystone.PutRequest
	(*PutResponse)(nil),      // 16: keystone.PutResponse
	(*DeleteRequest)(nil),    // 17: keystone.DeleteRequest
	(*DeleteResponse)(nil),   // 18: keystone.DeleteResponse
	(*CasRequest)(nil),       // 19: keystone.CasRequest
	(*CasResponse)(nil),      // 20: keystone.CasResponse
	(*ScanRequest)(nil),      // 21: keystone.ScanRequest
	(*ScanResponse)(nil),     // 22: keystone.ScanResponse
	(*NotLeader)(nil),        // 23: keystone.NotLeader
}
var file_kv_proto_depIdxs = []int32{
	2,  // 0: keystone.Command.register:type_name -> keystone.RegisterOp
	3,  // 1: keystone.Command.put:type_name -> keystone.PutOp
	4,  // 2: keystone.Command.delete:type_name -> keystone.DeleteOp
	5,  // 3: keystone.Command.cas:type_name -> keystone.CasOp
	6,  // 4: keystone.Command.get:type_name -> keystone.GetOp
	7,  // 5: keystone.Command.scan:type_name -> keystone.ScanOp
	8,  // 6: keystone.Result.kvs:type_name -> keystone.KeyValue
	0,  // 7: keystone.GetRequest.mode:type_name -> keystone.ReadMode
	10, // 8: keystone.GetRequest.session:type_name -> keystone.Session
	10, // 9: keystone.PutRequest.session:type_name -> keystone.Session
	10, // 10: keystone.DeleteRequest.session:type_name -> keystone.Session
	10, // 11: keystone.CasRequest.session:type_name -> keystone.Session
	0,  // 12: keystone.ScanRequest.mode:type_name -> keystone.ReadMode
	10, // 13: keystone.ScanRequest.session:type_name -> keystone.Session
	8,  // 14: keystone.ScanResponse.kvs:type_name -> keystone.KeyValue
	11, // 15: keystone.KV.Register:input_type -> keystone.RegisterRequest
	13, // 16: keystone.KV.Get:input_type -> keystone.GetRequest
	15, // 17: keystone.KV.Put:input_type -> keystone.PutRequest
	17, // 18: keystone.KV.Delete:input_type -> keystone.DeleteRequest
	19, // 19: keystone.KV.Cas:input_type -> keystone.CasRequest
	21, // 20: keystone.KV.Scan:input_type -> keystone.ScanRequest
	12, // 21: keystone.KV.Register:output_type -> keystone.RegisterResponse
	14, // 22: keystone.KV.Get:output_type -> keystone.GetResponse
	16, // 23: keystone.KV.Put:output_type -> keystone.PutResponse
	18, // 24: keystone.KV.Delete:output_type -> keystone.DeleteResponse
	20, // 25: keystone.KV.Cas:output_type -> keystone.CasResponse
	22, // 26: keystone.KV.Scan:output_type -> keystone.ScanResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_kv_proto_init() }
func file_kv_proto_init() {
	if File_kv_proto != nil {
		return
	}
	file_kv_proto_msgTypes[0].OneofWrappers = []any{
		(*Command_Register)(nil),
		(*Command_Put)(nil),
		(*Command_Delete)(nil),
		(*Command_Cas)(nil),
		(*Command_Get)(nil),
		(*Command_Scan)(nil),
	}
	file_kv_proto_msgTypes[4].OneofWrappers = []any{}
	file_kv_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kv_proto_goTypes,
		DependencyIndexes: file_kv_proto_depIdxs,
		EnumInfos:         file_kv_proto_enumTypes,
		MessageInfos:      file_kv_proto_msgTypes,
	}.Build()
	File_kv_proto = out.File
	file_kv_proto_goTypes = nil
	file_kv_proto_depIdxs = nil
}
