// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: raft.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *LogEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RaftMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         uint64                 `protobuf:"varint,16,opt,name=group,proto3" json:"group,omitempty"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	From          uint64                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To            uint64                 `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Term          uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	Index         uint64                 `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	LogTerm       uint64                 `protobuf:"varint,6,opt,name=log_term,json=logTerm,proto3" json:"log_term,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,7,rep,name=entries,proto3" json:"entries,omitempty"`
	Commit        uint64                 `protobuf:"varint,8,opt,name=commit,proto3" json:"commit,omitempty"`
	Reject        bool                   `protobuf:"varint,9,opt,name=reject,proto3" json:"reject,omitempty"`
	ConflictTerm  uint64                 `protobuf:"varint,10,opt,name=conflict_term,json=conflictTerm,proto3" json:"conflict_term,omitempty"`
	ConflictIndex uint64                 `protobuf:"varint,11,opt,name=conflict_index,json=conflictIndex,proto3" json:"conflict_index,omitempty"`
	ReadId        uint64                 `protobuf:"varint,12,opt,name=read_id,json=readId,proto3" json:"read_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,13,opt,name=data,proto3" json:"data,omitempty"`
	Offset        uint64                 `protobuf:"varint,14,opt,name=offset,proto3" json:"offset,omitempty"`
	Done          bool                   `protobuf:"varint,15,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{1}
}

func (x *RaftMessage) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *RaftMessage) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RaftMessage) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *RaftMessage) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *RaftMessage) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftMessage) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RaftMessage) GetLogTerm() uint64 {
	if x != nil {
		return x.LogTerm
	}
	return 0
}

func (x *RaftMessage) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *RaftMessage) GetCommit() uint64 {
	if x != nil {
		return x.Commit
	}
	return 0
}

func (x *RaftMessage) GetReject() bool {
	if x != nil {
		return x.Reject
	}
	return false
}

func (x *RaftMessage) GetConflictTerm() uint64 {
	if x != nil {
		return x.ConflictTerm
	}
	return 0
}

func (x *RaftMessage) GetConflictIndex() uint64 {
	if x != nil {
		return x.ConflictIndex
	}
	return 0
}

func (x *RaftMessage) GetReadId() uint64 {
	if x != nil {
		return x.ReadId
	}
	return 0
}

func (x *RaftMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RaftMessage) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RaftMessage) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type StreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{2}
}

var File_raft_proto protoreflect.FileDescriptor

const file_raft_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"raft.proto\x12\bkeystone\"\\\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\xa3\x03\n" +
	"\vRaftMessage\x12\x14\n" +
	"\x05group\x18\x10 \x01(\x04R\x05group\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x04R\x02to\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x05 \x01(\x04R\x05index\x12\x19\n" +
	"\blog_term\x18\x06 \x01(\x04R\alogTerm\x12,\n" +
	"\aentries\x18\a \x03(\v2\x12.keystone.LogEntryR\aentries\x12\x16\n" +
	"\x06commit\x18\b \x01(\x04R\x06commit\x12\x16\n" +
	"\x06reject\x18\t \x01(\bR\x06reject\x12#\n" +
	"\rconflict_term\x18\n" +
	" \x01(\x04R\fconflictTerm\x12%\n" +
	"\x0econflict_index\x18\v \x01(\x04R\rconflictIndex\x12\x17\n" +
	"\aread_id\x18\f \x01(\x04R\x06readId\x12\x12\n" +
	"\x04data\x18\r \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x0e \x01(\x04R\x06offset\x12\x12\n" +
	"\x04done\x18\x0f \x01(\bR\x04done\"\v\n" +
	"\tStreamAck2>\n" +
	"\x04Raft\x126\n" +
	"\x06Stream\x12\x15.keystone.RaftMessage\x1a\x13.keystone.StreamAck(\x01B'Z%github.com/arifisme/keystone/proto;pbb\x06proto3"

var (
	file_raft_proto_rawDescOnce sync.Once
	file_raft_proto_rawDescData []byte
)

func file_raft_proto_rawDescGZIP() []byte {
	file_raft_proto_rawDescOnce.Do(func() {
		file_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)))
	})
	return file_raft_proto_rawDescData
}

var file_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_raft_proto_goTypes = []any{
	(*LogEntry)(nil),    // 0: keystone.LogEntry
	(*RaftMessage)(nil), // 1: keystone.RaftMessage
	(*StreamAck)(nil),   // 2: keystone.StreamAck
}
var file_raft_proto_depIdxs = []int32{
	0, // 0: keystone.RaftMessage.entries:type_name -> keystone.LogEntry
	1, // 1: keystone.Raft.Stream:input_type -> keystone.RaftMessage
	2, // 2: keystone.Raft.Stream:output_type -> keystone.StreamAck
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_raft_proto_init() }
func file_raft_proto_init() {
	if File_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raft_proto_goTypes,
		DependencyIndexes: file_raft_proto_depIdxs,
		MessageInfos:      file_raft_proto_msgTypes,
	}.Build()
	File_raft_proto = out.File
	file_raft_proto_goTypes = nil
	file_raft_proto_depIdxs = nil
}
